#!/usr/bin/env bash
set -euo pipefail

# Separate Day-2 R40/R60/R75/R100 XGBoost training workflow.
# Event case V -> RAP V-1 09Z f03..f51 -> target V 12Z to V+1 12Z.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GENERATOR="make_run_hazard_ml_v33_day2_radius_sensitivity_from_WORKING_v28_radiusstats_SLIMMASTER_ROWSAMPLE.py"
REMOTE_PROJECT_DIR="/home/tyreekfrazier/ISU_Research/fall_2025_ml_proj"
LOCAL_PROJECT_DIR="/home/tyreekfrazier/ISU_Research_LOCAL_RUN/fall_2025_ml_proj"
if [[ -n "${HAZARD_ML_PROJECT_DIR:-}" ]]; then
  PROJECT_DIR="${HAZARD_ML_PROJECT_DIR}"
elif [[ -d "${REMOTE_PROJECT_DIR}" ]]; then
  PROJECT_DIR="${REMOTE_PROJECT_DIR}"
elif [[ -d "${LOCAL_PROJECT_DIR}" ]]; then
  PROJECT_DIR="${LOCAL_PROJECT_DIR}"
else
  PROJECT_DIR="${REMOTE_PROJECT_DIR}"
fi
LOG_DIR="${PROJECT_DIR}/training_logs"
mkdir -p "${LOG_DIR}"

export HAZARD_ML_SCRIPT_DIR="${SCRIPT_DIR}"
export HAZARD_ML_PROJECT_DIR="${PROJECT_DIR}"
export HAZARD_ML_BASE_V28_RADIUSSTATS_SCRIPT="${HAZARD_ML_BASE_V28_RADIUSSTATS_SCRIPT:-${SCRIPT_DIR}/hazard_ml_training_v28_r100km_singletarget_radiusstats_regression_MEMSAFE_V3.py}"
export HAZARD_ML_V33_DAY2_GENERATED_SCRIPT_DIR="${HAZARD_ML_V33_DAY2_GENERATED_SCRIPT_DIR:-${SCRIPT_DIR}/generated_v33_day2_radius_sensitivity_slimmaster_rowsample}"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"
export HAZARD_ML_RAY_USE_GPUS="${HAZARD_ML_RAY_USE_GPUS:-0}"
if [[ "${HAZARD_ML_RAY_USE_GPUS}" != "1" ]]; then
  export CUDA_VISIBLE_DEVICES=""
  export NVIDIA_VISIBLE_DEVICES=""
fi

export HAZARD_ML_FORCE_FRESH_RUN="${HAZARD_ML_FORCE_FRESH_RUN:-0}"
export HAZARD_ML_FORCE_RETRAIN_MODEL="${HAZARD_ML_FORCE_RETRAIN_MODEL:-1}"
export HAZARD_ML_DAY2_RESUME_CACHED_CHUNKS="${HAZARD_ML_DAY2_RESUME_CACHED_CHUNKS:-1}"
export HAZARD_ML_USE_RAY_FOR_DATA_EXTRACTION="${HAZARD_ML_USE_RAY_FOR_DATA_EXTRACTION:-0}"
export HAZARD_ML_RAY_MAX_IN_FLIGHT="${HAZARD_ML_RAY_MAX_IN_FLIGHT:-2}"
export HAZARD_ML_LOCAL_MODEL_N_JOBS="${HAZARD_ML_LOCAL_MODEL_N_JOBS:-1}"
export HAZARD_ML_LOCAL_OPTUNA_XGB_TRIALS="${HAZARD_ML_LOCAL_OPTUNA_XGB_TRIALS:-30}"
export HAZARD_ML_LOCAL_TUNE_MAX_TRAIN_ROWS_PER_FOLD="${HAZARD_ML_LOCAL_TUNE_MAX_TRAIN_ROWS_PER_FOLD:-300000}"
export HAZARD_ML_LOCAL_TUNE_MAX_VAL_ROWS_PER_FOLD="${HAZARD_ML_LOCAL_TUNE_MAX_VAL_ROWS_PER_FOLD:-100000}"

export HAZARD_ML_MASTER_COMBINE_BATCH_SIZE="${HAZARD_ML_MASTER_COMBINE_BATCH_SIZE:-2}"
export HAZARD_ML_MASTER_COMBINE_SLIM_WRITE="${HAZARD_ML_MASTER_COMBINE_SLIM_WRITE:-1}"
export HAZARD_ML_MASTER_SLIM_READ="${HAZARD_ML_MASTER_SLIM_READ:-1}"
export HAZARD_ML_MASTER_STREAM_ROW_SAMPLE="${HAZARD_ML_MASTER_STREAM_ROW_SAMPLE:-1}"
export HAZARD_ML_MASTER_MAX_TRAIN_ROWS="${HAZARD_ML_MASTER_MAX_TRAIN_ROWS:-800000}"
export HAZARD_ML_MASTER_MAX_TEST_ROWS="${HAZARD_ML_MASTER_MAX_TEST_ROWS:-200000}"
export HAZARD_ML_SKIP_MASTER_FEATURE_REENGINEERING="${HAZARD_ML_SKIP_MASTER_FEATURE_REENGINEERING:-1}"

export RADIUS_LIST="${RADIUS_LIST:-40 60 75 100}"
export FORCE_RERUN="${FORCE_RERUN:-0}"
export FEATURE_RADIUS_FOLLOWS_TARGET="${FEATURE_RADIUS_FOLLOWS_TARGET:-1}"

cd "${SCRIPT_DIR}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Starting separate v33 Day-2 radius workflow"
echo "Case date V is the event-valid start; RAP initialization is V-1 at 09Z"
echo "RAP offsets: 0 6 12 18 24 30 36 42 48 (files f03..f51)"
echo "Target: MRMS >= FFG from case V 12Z through V+1 12Z"
echo "Project directory: ${PROJECT_DIR}"
echo "RADIUS_LIST=${RADIUS_LIST}"
echo "Resume from cached daily chunks=${HAZARD_ML_DAY2_RESUME_CACHED_CHUNKS}"
echo "Optuna XGBoost trials=${HAZARD_ML_LOCAL_OPTUNA_XGB_TRIALS}"

python -u "${GENERATOR}" 2>&1 | tee "${LOG_DIR}/hazard_ml_v33_day2_radiusstats_$(date -u +%Y%m%d_%H%M%S).log"
